// import {
// FlagAfghanistanIcon,
// FlagAlandIslandsIcon,
// FlagAlbaniaIcon,
// FlagAlgeriaIcon,
// FlagAmericanSamoaIcon,
// FlagAndorraIcon,
// FlagAngolaIcon,
// FlagAnguillaIcon,
// FlagAntarcticaIcon,
// FlagAntiguaAndBarbudaIcon,
// FlagArgentinaIcon,
// FlagArmeniaIcon,
// FlagArubaIcon,
// FlagAustraliaIcon,
// FlagAustriaIcon,
// FlagAzerbaijanIcon,
// FlagBahamasIcon,
// FlagBahrainIcon,
// FlagBangladeshIcon,
// FlagBarbadosIcon,
// FlagBelarusIcon,
// FlagBelgiumIcon,
// FlagBelizeIcon,
// FlagBeninIcon,
// FlagBermudaIcon,
// FlagBhutanIcon,
// FlagBoliviaIcon,
// FlagBonaireIcon,
// FlagBosniaAndHerzegovinaIcon,
// FlagBotswanaIcon,
// FlagBouvetIslandIcon,
// FlagBrazilIcon,
// FlagBritishIndianOceanTerritoryIcon,
// FlagBritishVirginIslandsIcon,
// FlagBruneiIcon,
// FlagBulgariaIcon,
// FlagBurkinaFasoIcon,
// FlagBurundiIcon,
// FlagCTeDIvoireIcon,
// FlagCambodiaIcon,
// FlagCameroonIcon,
// FlagCanadaIcon,
// FlagCapeVerdeIcon,
// FlagCaymanIslandsIcon,
// FlagCentralAfricanRepublicIcon,
// FlagChadIcon,
// FlagChileIcon,
// FlagChinaIcon,
// FlagChristmasIslandIcon,
// FlagCocosKeelingIslandsIcon,
// FlagColombiaIcon,
// FlagComorosIcon,
// FlagCongoBrazzavilleIcon,
// FlagCongoKinshasaIcon,
// FlagCookIslandsIcon,
// FlagCostaRicaIcon,
// FlagCroatiaIcon,
// FlagCubaIcon,
// FlagCuracaoIcon,
// FlagCyprusIcon,
// FlagCzechRepublicIcon,
// FlagDenmarkIcon,
// FlagDjiboutiIcon,
// FlagDominicaIcon,
// FlagDomincanRepublicIcon,
// FlagEcuadorIcon,
// FlagEgyptIcon,
// FlagElSalvadorIcon,
// FlagEquatorialGuineaIcon,
// FlagEritreaIcon,
// FlagEstoniaIcon,
// FlagEthiopiaIcon,
// FlagFalklandIslandsIcon,
// FlagFijiIcon,
// FlagFinlandIcon,
// FlagFranceIcon,
// FlagFrenchGuianaIcon,
// FlagFrenchPolynesiaIcon,
// FlagFrenchSouthernAndAntarcticLandsIcon,
// FlagGabonIcon,
// FlagGambiaIcon,
// FlagGeorgiaIcon,
// FlagGermanyIcon,
// FlagGhanaIcon,
// FlagGibraltarIcon,
// FlagGreeceIcon,
// FlagGreenlandIcon,
// FlagGrenadaIcon,
// FlagGuadeloupe1Icon,
// FlagGuamIcon,
// FlagGuatemalaIcon,
// FlagGuernseyIcon,
// FlagGuineaIcon,
// FlagGuineaBissauIcon,
// FlagGuyanaIcon,
// FlagHaitiIcon,
// FlagHeardAndMcdonaldIslandsIcon,
// FlagHondurasIcon,
// FlagHongKongIcon,
// FlagHungaryIcon,
// FlagIcelandIcon,
// FlagIndiaIcon,
// FlagIndonesiaIcon,
// FlagIranIcon,
// FlagIraqIcon,
// FlagIrelandIcon,
// FlagIsleOfManIcon,
// FlagIsraelIcon,
// FlagItalyIcon,
// FlagJamaicaIcon,
// FlagJapanIcon,
// FlagJerseyIcon,
// FlagJordanIcon,
// FlagKazakhstanIcon,
// FlagKenyaIcon,
// FlagKiribatiIcon,
// FlagKuwaitIcon,
// FlagKyrgyzstanIcon,
// FlagLaosIcon,
// FlagLatviaIcon,
// FlagLebanonIcon,
// FlagLesothoIcon,
// FlagLiberiaIcon,
// FlagLibyaIcon,
// FlagLiechtensteinIcon,
// FlagLithuaniaIcon,
// FlagLuxembourgIcon,
// FlagMacauIcon,
// FlagMacedoniaIcon,
// FlagMadagascarIcon,
// FlagMalawiIcon,
// FlagMalaysiaIcon,
// FlagMaldivesIcon,
// FlagMaliIcon,
// FlagMaltaIcon,
// FlagMarshallIslandsIcon,
// FlagMartiniqueIcon,
// FlagMauritaniaIcon,
// FlagMauritiusIcon,
// FlagMayotteIcon,
// FlagMexicoIcon,
// FlagMicronesiaIcon,
// FlagMoldovaIcon,
// FlagMonacoIcon,
// FlagMongoliaIcon,
// FlagMontenegroIcon,
// FlagMontserratIcon,
// FlagMoroccoIcon,
// FlagMozambiqueIcon,
// FlagMyanmarIcon,
// FlagNamibiaIcon,
// FlagNauruIcon,
// FlagNepalIcon,
// FlagNetherlandIcon,
// FlagNetherlandsAntillesIcon,
// FlagNewCaledoniaIcon,
// FlagNewZealandIcon,
// FlagNicaraguaIcon,
// FlagNigerIcon,
// FlagNigeriaIcon,
// FlagNiueIcon,
// FlagNorfolkIslandsIcon,
// FlagNorthKoreaIcon,
// FlagNorthernMarianaIslandsIcon,
// FlagNorwayIcon,
// FlagOmanIcon,
// FlagPakistanIcon,
// FlagPalauIcon,
// FlagPalestineIcon,
// FlagPanamaIcon,
// FlagPapuaNewGuineaIcon,
// FlagParaguayIcon,
// FlagPeruIcon,
// FlagPhilippinesIcon,
// FlagPitcairnIslandsIcon,
// FlagPolandIcon,
// FlagPortugalIcon,
// FlagPuertoRicoIcon,
// FlagQatarIcon,
// FlagRUnionIcon,
// FlagRomaniaIcon,
// FlagRussiaIcon,
// FlagRwandaIcon,
// FlagSaintBarthelemyIcon,
// FlagSaintHelenaIcon,
// FlagSaintKittsAndNevisIcon,
// FlagSaintLuciaIcon,
// FlagSaintMartinIcon,
// FlagSaintPierreAndMiquelonIcon,
// FlagSaintVincentAndGrenadinesIcon,
// FlagSamoaIcon,
// FlagSanMarinoIcon,
// FlagSaoTomeAndPrincipeIcon,
// FlagSaudiArabiaIcon,
// FlagSeirraLeoneIcon,
// FlagSenegalIcon,
// FlagSerbiaIcon,
// FlagSeychellesIcon,
// FlagSingaporeIcon,
// FlagSintMaartenIcon,
// FlagSlovakiaIcon,
// FlagSloveniaIcon,
// FlagSolomonIslandsIcon,
// FlagSomaliaIcon,
// FlagSouthAfricaIcon,
// FlagSouthGeorgiaAndTheSouthSandwichIslandsIcon,
// FlagSouthKoreaIcon,
// FlagSouthSudanIcon,
// FlagSpainIcon,
// FlagSriLankaIcon,
// FlagSudanIcon,
// FlagSurinameIcon,
// FlagSvalbardAndJanMayenIcon,
// FlagSwazilandIcon,
// FlagSwedenIcon,
// FlagSwitzerlandIcon,
// FlagSyriaIcon,
// FlagTaiwanIcon,
// FlagTajikistanIcon,
// FlagTanzaniaIcon,
// FlagThailandIcon,
// FlagTimorLesteIcon,
// FlagTogoIcon,
// FlagTokelauIcon,
// FlagTongaIcon,
// FlagTrinidadAndTobagoIcon,
// FlagTunisiaIcon,
// FlagTurkeyIcon,
// FlagTurkmenistanIcon,
// FlagTurksAndCaicosIslandsIcon,
// FlagTuvaluIcon,
// FlagUSVirginIslandsIcon,
// FlagUgandaIcon,
// FlagUkraineIcon,
// FlagUruguayIcon,
// FlagUnitedArabEmiratesIcon,
// FlagUnitedKingdomIcon,
// FlagUsaIcon,
// FlagUzbekistanIcon,
// FlagVanuatuIcon,
// FlagVaticanCityIcon,
// FlagVenezuelaIcon,
// FlagVietnamIcon,
// FlagWallisAndFutunaIcon,
// FlagWesternSaharaIcon,
// FlagYemenIcon,
// FlagZambiaIcon,
// FlagZimbabweIcon,
// } from "@deriv/quill-icons/Flags";

// Commenting these out to reduce the bundle size might need it later
// AF: <FlagAfghanistanIcon />,
// AX: <FlagAlandIslandsIcon />,
// AL: <FlagAlbaniaIcon />,
// DZ: <FlagAlgeriaIcon />,
// AS: <FlagAmericanSamoaIcon />,
// AD: <FlagAndorraIcon />,
// AO: <FlagAngolaIcon />,
// AI: <FlagAnguillaIcon />,
// AQ: <FlagAntarcticaIcon />,
// AG: <FlagAntiguaAndBarbudaIcon />,
// AR: <FlagArgentinaIcon />,
// AM: <FlagArmeniaIcon />,
// AW: <FlagArubaIcon />,
// AU: <FlagAustraliaIcon />,
// AT: <FlagAustriaIcon />,
// AZ: <FlagAzerbaijanIcon />,
// BS: <FlagBahamasIcon />,
// BH: <FlagBahrainIcon />,
// BD: <FlagBangladeshIcon />,
// BB: <FlagBarbadosIcon />,
// BY: <FlagBelarusIcon />,
// BE: <FlagBelgiumIcon />,
// BZ: <FlagBelizeIcon />,
// BJ: <FlagBeninIcon />,
// BM: <FlagBermudaIcon />,
// BT: <FlagBhutanIcon />,
// BO: <FlagBoliviaIcon />,
// BQ: <FlagBonaireIcon />,
// BA: <FlagBosniaAndHerzegovinaIcon />,
// BW: <FlagBotswanaIcon />,
// BV: <FlagBouvetIslandIcon />,
// BR: <FlagBrazilIcon />,
// IO: <FlagBritishIndianOceanTerritoryIcon />,
// VG: <FlagBritishVirginIslandsIcon />,
// BN: <FlagBruneiIcon />,
// BG: <FlagBulgariaIcon />,
// BF: <FlagBurkinaFasoIcon />,
// BI: <FlagBurundiIcon />,
// CI: <FlagCTeDIvoireIcon />,
// KH: <FlagCambodiaIcon />,
// CM: <FlagCameroonIcon />,
// CA: <FlagCanadaIcon />,
// CV: <FlagCapeVerdeIcon />,
// KY: <FlagCaymanIslandsIcon />,
// CF: <FlagCentralAfricanRepublicIcon />,
// TD: <FlagChadIcon />,
// CL: <FlagChileIcon />,
// CN: <FlagChinaIcon />,
// CX: <FlagChristmasIslandIcon />,
// CC: <FlagCocosKeelingIslandsIcon />,
// CO: <FlagColombiaIcon />,
// KM: <FlagComorosIcon />,
// CG: <FlagCongoBrazzavilleIcon />,
// CD: <FlagCongoKinshasaIcon />,
// CK: <FlagCookIslandsIcon />,
// CR: <FlagCostaRicaIcon />,
// HR: <FlagCroatiaIcon />,
// CU: <FlagCubaIcon />,
// CW: <FlagCuracaoIcon />,
// CY: <FlagCyprusIcon />,
// CZ: <FlagCzechRepublicIcon />,
// DK: <FlagDenmarkIcon />,
// DJ: <FlagDjiboutiIcon />,
// DM: <FlagDominicaIcon />,
// DO: <FlagDomincanRepublicIcon />,
// EC: <FlagEcuadorIcon />,
// EG: <FlagEgyptIcon />,
// SV: <FlagElSalvadorIcon />,
// GQ: <FlagEquatorialGuineaIcon />,
// ER: <FlagEritreaIcon />,
// EE: <FlagEstoniaIcon />,
// ET: <FlagEthiopiaIcon />,
// FK: <FlagFalklandIslandsIcon />,
// FJ: <FlagFijiIcon />,
// FI: <FlagFinlandIcon />,
// FR: <FlagFranceIcon />,
// GF: <FlagFrenchGuianaIcon />,
// PF: <FlagFrenchPolynesiaIcon />,
// TF: <FlagFrenchSouthernAndAntarcticLandsIcon />,
// GA: <FlagGabonIcon />,
// GM: <FlagGambiaIcon />,
// GE: <FlagGeorgiaIcon />,
// DE: <FlagGermanyIcon />,
// GH: <FlagGhanaIcon />,
// GI: <FlagGibraltarIcon />,
// GR: <FlagGreeceIcon />,
// GL: <FlagGreenlandIcon />,
// GD: <FlagGrenadaIcon />,
// GP: <FlagGuadeloupe1Icon />,
// GU: <FlagGuamIcon />,
// GT: <FlagGuatemalaIcon />,
// GG: <FlagGuernseyIcon />,
// GN: <FlagGuineaIcon />,
// GW: <FlagGuineaBissauIcon />,
// GY: <FlagGuyanaIcon />,
// HT: <FlagHaitiIcon />,
// HM: <FlagHeardAndMcdonaldIslandsIcon />,
// HN: <FlagHondurasIcon />,
// HK: <FlagHongKongIcon />,
// HU: <FlagHungaryIcon />,
// IS: <FlagIcelandIcon />,
// IN: <FlagIndiaIcon />,
// ID: <FlagIndonesiaIcon />,
// IR: <FlagIranIcon />,
// IQ: <FlagIraqIcon />,
// IE: <FlagIrelandIcon />,
// IM: <FlagIsleOfManIcon />,
// IL: <FlagIsraelIcon />,
// IT: <FlagItalyIcon />,
// JM: <FlagJamaicaIcon />,
// JP: <FlagJapanIcon />,
// JE: <FlagJerseyIcon />,
// JO: <FlagJordanIcon />,
// KZ: <FlagKazakhstanIcon />,
// KE: <FlagKenyaIcon />,
// KI: <FlagKiribatiIcon />,
// KW: <FlagKuwaitIcon />,
// KG: <FlagKyrgyzstanIcon />,
// LA: <FlagLaosIcon />,
// LV: <FlagLatviaIcon />,
// LB: <FlagLebanonIcon />,
// LS: <FlagLesothoIcon />,
// LR: <FlagLiberiaIcon />,
// LY: <FlagLibyaIcon />,
// LI: <FlagLiechtensteinIcon />,
// LT: <FlagLithuaniaIcon />,
// LU: <FlagLuxembourgIcon />,
// MO: <FlagMacauIcon />,
// MK: <FlagMacedoniaIcon />,
// MG: <FlagMadagascarIcon />,
// MW: <FlagMalawiIcon />,
// MY: <FlagMalaysiaIcon />,
// MV: <FlagMaldivesIcon />,
// ML: <FlagMaliIcon />,
// MT: <FlagMaltaIcon />,
// MH: <FlagMarshallIslandsIcon />,
// MQ: <FlagMartiniqueIcon />,
// MR: <FlagMauritaniaIcon />,
// MU: <FlagMauritiusIcon />,
// YT: <FlagMayotteIcon />,
// MX: <FlagMexicoIcon />,
// FM: <FlagMicronesiaIcon />,
// MD: <FlagMoldovaIcon />,
// MC: <FlagMonacoIcon />,
// MN: <FlagMongoliaIcon />,
// ME: <FlagMontenegroIcon />,
// MS: <FlagMontserratIcon />,
// MA: <FlagMoroccoIcon />,
// MZ: <FlagMozambiqueIcon />,
// MM: <FlagMyanmarIcon />,
// NA: <FlagNamibiaIcon />,
// NR: <FlagNauruIcon />,
// NP: <FlagNepalIcon />,
// NL: <FlagNetherlandIcon />,
// AN: <FlagNetherlandsAntillesIcon />,
// NC: <FlagNewCaledoniaIcon />,
// NZ: <FlagNewZealandIcon />,
// NI: <FlagNicaraguaIcon />,
// NE: <FlagNigerIcon />,
// NG: <FlagNigeriaIcon />,
// NU: <FlagNiueIcon />,
// NF: <FlagNorfolkIslandsIcon />,
// KP: <FlagNorthKoreaIcon />,
// MP: <FlagNorthernMarianaIslandsIcon />,
// NO: <FlagNorwayIcon />,
// OM: <FlagOmanIcon />,
// PK: <FlagPakistanIcon />,
// PW: <FlagPalauIcon />,
// PS: <FlagPalestineIcon />,
// PA: <FlagPanamaIcon />,
// PG: <FlagPapuaNewGuineaIcon />,
// PY: <FlagParaguayIcon />,
// PE: <FlagPeruIcon />,
// PH: <FlagPhilippinesIcon />,
// PN: <FlagPitcairnIslandsIcon />,
// PL: <FlagPolandIcon />,
// PT: <FlagPortugalIcon />,
// PR: <FlagPuertoRicoIcon />,
// QA: <FlagQatarIcon />,
// RE: <FlagRUnionIcon />,
// RO: <FlagRomaniaIcon />,
// RU: <FlagRussiaIcon />,
// RW: <FlagRwandaIcon />,
// BL: <FlagSaintBarthelemyIcon />,
// SH: <FlagSaintHelenaIcon />,
// KN: <FlagSaintKittsAndNevisIcon />,
// LC: <FlagSaintLuciaIcon />,
// MF: <FlagSaintMartinIcon />,
// PM: <FlagSaintPierreAndMiquelonIcon />,
// VC: <FlagSaintVincentAndGrenadinesIcon />,
// WS: <FlagSamoaIcon />,
// SM: <FlagSanMarinoIcon />,
// ST: <FlagSaoTomeAndPrincipeIcon />,
// SA: <FlagSaudiArabiaIcon />,
// SL: <FlagSeirraLeoneIcon />,
// SN: <FlagSenegalIcon />,
// RS: <FlagSerbiaIcon />,
// SC: <FlagSeychellesIcon />,
// SG: <FlagSingaporeIcon />,
// SX: <FlagSintMaartenIcon />,
// SK: <FlagSlovakiaIcon />,
// SI: <FlagSloveniaIcon />,
// SB: <FlagSolomonIslandsIcon />,
// SO: <FlagSomaliaIcon />,
// ZA: <FlagSouthAfricaIcon />,
// GS: <FlagSouthGeorgiaAndTheSouthSandwichIslandsIcon />,
// KR: <FlagSouthKoreaIcon />,
// SS: <FlagSouthSudanIcon />,
// ES: <FlagSpainIcon />,
// LK: <FlagSriLankaIcon />,
// SD: <FlagSudanIcon />,
// SR: <FlagSurinameIcon />,
// SJ: <FlagSvalbardAndJanMayenIcon />,
// SZ: <FlagSwazilandIcon />,
// SE: <FlagSwedenIcon />,
// CH: <FlagSwitzerlandIcon />,
// SY: <FlagSyriaIcon />,
// TW: <FlagTaiwanIcon />,
// TJ: <FlagTajikistanIcon />,
// TZ: <FlagTanzaniaIcon />,
// TH: <FlagThailandIcon />,
// TL: <FlagTimorLesteIcon />,
// TG: <FlagTogoIcon />,
// TK: <FlagTokelauIcon />,
// TO: <FlagTongaIcon />,
// TT: <FlagTrinidadAndTobagoIcon />,
// TN: <FlagTunisiaIcon />,
// TR: <FlagTurkeyIcon />,
// TM: <FlagTurkmenistanIcon />,
// TC: <FlagTurksAndCaicosIslandsIcon />,
// TV: <FlagTuvaluIcon />,
// VI: <FlagUSVirginIslandsIcon />,
// UG: <FlagUgandaIcon />,
// UA: <FlagUkraineIcon />,
// UY: <FlagUruguayIcon />,
// AE: <FlagUnitedArabEmiratesIcon />,
// GB: <FlagUnitedKingdomIcon />,
// US: <FlagUsaIcon />,
// UZ: <FlagUzbekistanIcon />,
// VU: <FlagVanuatuIcon />,
// VA: <FlagVaticanCityIcon />,
// VE: <FlagVenezuelaIcon />,
// VN: <FlagVietnamIcon />,
// WF: <FlagWallisAndFutunaIcon />,
// EH: <FlagWesternSaharaIcon />,
// YE: <FlagYemenIcon />,
// ZM: <FlagZambiaIcon />,
// ZW: <FlagZimbabweIcon />,

import { FlagPlaceholderIcon } from "@deriv/quill-icons/Flags";
import React, { ReactNode } from "react";

export const FlagsMap: Record<string, ReactNode> = {
    XX: <FlagPlaceholderIcon />,
};
