import React from "react";
import {
    FlagAfghanistanIcon,
    FlagAlbaniaIcon,
    FlagAndorraIcon,
    FlagAngolaIcon,
    FlagAntiguaAndBarbudaIcon,
    FlagArgentinaIcon,
    FlagArmeniaIcon,
    FlagArubaIcon,
    FlagAustraliaIcon,
    FlagAustriaIcon,
    FlagAzerbaijanIcon,
    FlagBahamasIcon,
    FlagBahrainIcon,
    FlagBangladeshIcon,
    FlagBarbadosIcon,
    FlagBelarusIcon,
    FlagBelgiumIcon,
    FlagBelizeIcon,
    FlagBeninIcon,
    FlagBhutanIcon,
    FlagBoliviaIcon,
    FlagBosniaAndHerzegovinaIcon,
    FlagBotswanaIcon,
    FlagBouvetIslandIcon,
    FlagBrazilIcon,
    FlagBritishVirginIslandsIcon,
    FlagBruneiIcon,
    FlagBulgariaIcon,
    FlagBurkinaFasoIcon,
    FlagCambodiaIcon,
    FlagCanadaIcon,
    FlagCaymanIslandsIcon,
    FlagCentralAfricanRepublicIcon,
    FlagChannelIslandsIcon,
    FlagChinaIcon,
    FlagCroatiaIcon,
    FlagCyprusIcon,
    FlagCzechRepublicIcon,
    FlagDemocraticRepublicOfTheCongoIcon,
    FlagDenmarkIcon,
    FlagEstoniaIcon,
    FlagFinlandIcon,
    FlagFranceIcon,
    FlagGermanyIcon,
    FlagGreeceIcon,
    FlagHongKongIcon,
    FlagHungaryIcon,
    FlagIndiaIcon,
    FlagIndonesiaIcon,
    FlagIrelandIcon,
    FlagIsraelIcon,
    FlagItalyIcon,
    FlagJapanIcon,
    FlagJordanIcon,
    FlagKenyaIcon,
    FlagLatviaIcon,
    FlagLithuaniaIcon,
    FlagLuxembourgIcon,
    FlagMalaysiaIcon,
    FlagMaltaIcon,
    FlagMexicoIcon,
    FlagMongoliaIcon,
    FlagNetherlandIcon,
    FlagNetherlandsAntillesIcon,
    FlagNewZealandIcon,
    FlagNigeriaIcon,
    FlagNorwayIcon,
    FlagPakistanIcon,
    FlagParaguayIcon,
    FlagPlaceholderIcon,
    FlagPolandIcon,
    FlagPortugalIcon,
    FlagRomaniaIcon,
    FlagRussiaIcon,
    FlagRwandaIcon,
    FlagSenegalIcon,
    FlagSingaporeIcon,
    FlagSlovakiaIcon,
    FlagSloveniaIcon,
    FlagSouthAfricaIcon,
    FlagSpainIcon,
    FlagSriLankaIcon,
    FlagSwedenIcon,
    FlagSwitzerlandIcon,
    FlagTaiwanIcon,
    FlagTanzaniaIcon,
    FlagThailandIcon,
    FlagTurkeyIcon,
    FlagUnitedArabEmiratesIcon,
    FlagUnitedKingdomIcon,
    FlagUsaIcon,
    FlagUzbekistanIcon,
    FlagVanuatuIcon,
    FlagVietnamIcon,
} from "@deriv/quill-icons/Flags";
import { ReactNode } from "react";

export const FlagsMap: Record<string, ReactNode> = {
    XX: <FlagPlaceholderIcon />,
    AF: <FlagAfghanistanIcon />,
    AL: <FlagAlbaniaIcon />,
    AD: <FlagAndorraIcon />,
    AO: <FlagAngolaIcon />,
    AG: <FlagAntiguaAndBarbudaIcon />,
    AR: <FlagArgentinaIcon />,
    AM: <FlagArmeniaIcon />,
    AW: <FlagArubaIcon />,
    AU: <FlagAustraliaIcon />,
    AT: <FlagAustriaIcon />,
    AZ: <FlagAzerbaijanIcon />,
    BS: <FlagBahamasIcon />,
    BH: <FlagBahrainIcon />,
    BD: <FlagBangladeshIcon />,
    BB: <FlagBarbadosIcon />,
    BY: <FlagBelarusIcon />,
    BE: <FlagBelgiumIcon />,
    BZ: <FlagBelizeIcon />,
    BJ: <FlagBeninIcon />,
    BT: <FlagBhutanIcon />,
    BO: <FlagBoliviaIcon />,
    BA: <FlagBosniaAndHerzegovinaIcon />,
    BW: <FlagBotswanaIcon />,
    BV: <FlagBouvetIslandIcon />,
    BR: <FlagBrazilIcon />,
    VG: <FlagBritishVirginIslandsIcon />,
    BN: <FlagBruneiIcon />,
    BG: <FlagBulgariaIcon />,
    BF: <FlagBurkinaFasoIcon />,
    KH: <FlagCambodiaIcon />,
    CA: <FlagCanadaIcon />,
    KY: <FlagCaymanIslandsIcon />,
    CF: <FlagCentralAfricanRepublicIcon />,
    CI: <FlagChannelIslandsIcon />,
    CN: <FlagChinaIcon />,
    HR: <FlagCroatiaIcon />,
    CY: <FlagCyprusIcon />,
    CZ: <FlagCzechRepublicIcon />,
    CD: <FlagDemocraticRepublicOfTheCongoIcon />,
    DK: <FlagDenmarkIcon />,
    EE: <FlagEstoniaIcon />,
    FI: <FlagFinlandIcon />,
    FR: <FlagFranceIcon />,
    DE: <FlagGermanyIcon />,
    GR: <FlagGreeceIcon />,
    HK: <FlagHongKongIcon />,
    HU: <FlagHungaryIcon />,
    IN: <FlagIndiaIcon />,
    ID: <FlagIndonesiaIcon />,
    IE: <FlagIrelandIcon />,
    IL: <FlagIsraelIcon />,
    IT: <FlagItalyIcon />,
    JP: <FlagJapanIcon />,
    JO: <FlagJordanIcon />,
    KE: <FlagKenyaIcon />,
    LV: <FlagLatviaIcon />,
    LT: <FlagLithuaniaIcon />,
    LU: <FlagLuxembourgIcon />,
    MY: <FlagMalaysiaIcon />,
    MT: <FlagMaltaIcon />,
    MX: <FlagMexicoIcon />,
    MN: <FlagMongoliaIcon />,
    NL: <FlagNetherlandIcon />,
    AN: <FlagNetherlandsAntillesIcon />,
    NZ: <FlagNewZealandIcon />,
    NG: <FlagNigeriaIcon />,
    NO: <FlagNorwayIcon />,
    PK: <FlagPakistanIcon />,
    PY: <FlagParaguayIcon />,
    PL: <FlagPolandIcon />,
    PT: <FlagPortugalIcon />,
    RO: <FlagRomaniaIcon />,
    RU: <FlagRussiaIcon />,
    RW: <FlagRwandaIcon />,
    SN: <FlagSenegalIcon />,
    SG: <FlagSingaporeIcon />,
    SK: <FlagSlovakiaIcon />,
    SI: <FlagSloveniaIcon />,
    ZA: <FlagSouthAfricaIcon />,
    ES: <FlagSpainIcon />,
    LK: <FlagSriLankaIcon />,
    SE: <FlagSwedenIcon />,
    CH: <FlagSwitzerlandIcon />,
    TW: <FlagTaiwanIcon />,
    TZ: <FlagTanzaniaIcon />,
    TH: <FlagThailandIcon />,
    TR: <FlagTurkeyIcon />,
    AE: <FlagUnitedArabEmiratesIcon />,
    GB: <FlagUnitedKingdomIcon />,
    US: <FlagUsaIcon />,
    UZ: <FlagUzbekistanIcon />,
    VU: <FlagVanuatuIcon />,
    VN: <FlagVietnamIcon />,
};
